GET http://localhost:5000/
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjUzMTQxNzAsImV4cCI6MTY2NTMxNzc3MCwiYXVkIjoiMTAxIn0.WBdAMKxH2WCgK8XTcc1Bg9QdfT0aFJPBkKDiEs22UF0

###
GET http://localhost:5000/type_dossiers/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjUzMTQxNzAsImV4cCI6MTY2NTMxNzc3MCwiYXVkIjoiMTAxIn0.WBdAMKxH2WCgK8XTcc1Bg9QdfT0aFJPBkKDiEs22UF0

###Login Route
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "66660600005mmaamm06aa67777a77778888889998880000000000000",
  "password": "1234"
}


###Register Route
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "66660600005mmaamm06aa67777a77778888889998880000000000000",
  "password": "1234"
}


###Refresh token Route
POST http://localhost:5000/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjUzMTA4ODcsImV4cCI6MTY5Njg2ODQ4NywiYXVkIjoiOTUifQ.iCAB-O9FeuVoD5QYDtV3DdHsK4zKiET7MtEiQQCi3ik"
}

###Logout Route
DELETE http://localhost:5000/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjUzMTI5ODAsImV4cCI6MTY5Njg3MDU4MCwiYXVkIjoiMTAxIn0.B7dMWqXfTLF1Z_arRvZMCcFB3WBRVau2209qQGDQvW0"
}


